server:
  port: 8082

spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oromart?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 111111
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms     # 连接超时时间（毫秒） 建立连接的最长的等待时间。使用负值无限期等待
      lettuce:
        pool:
          max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8     # 连接池中的最大空闲连接
          min-idle: 0     # 连接池中的最小空闲连接
          max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  threads:
    virtual:
      enabled: true
  cloud:
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  token-name: satoken		# token 名称（同时也是 cookie 名称）
  timeout: 2592000			# token 有效期（单位：秒） 默认30天，-1 代表永久有效
  active-timeout: -1		# token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  is-concurrent: true		# 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-share: false				# 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  token-style: uuid			# token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  is-log: true					# 是否输出操作日志